# Values for Config Server
replicaCount: 1

image:
  repository: kkkkk854/config-server
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "config-server"
fullnameOverride: "config-server"

service:
  type: NodePort
  port: 8888

# Health checks for Spring Boot Actuator
# livenessProbe:
#   httpGet:
#     path: /actuator/health/liveness
#     port: 8888
#   initialDelaySeconds: 60
#   periodSeconds: 30

# readinessProbe:
#   httpGet:
#     path: /actuator/health/readiness
#     port: 8888
#   initialDelaySeconds: 30
#   periodSeconds: 10

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Environment variables
env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s"
